create type TYPE_WATER as enum ('HOT', 'COLD');
create type TYPE_BILLS as enum ('PRODUCTS', 'CLOTHES', 'CAR', 'INTERNET', 'KINDERGARTEN', 'APARTMENT', 'OTHER');


CREATE TABLE IF NOT EXISTS WATER_METER
(
    ID BIGSERIAL PRIMARY KEY,
    TYPE_WATER TYPE_WATER,
    METER_READING DECIMAL(5, 3) NOT NULL,
    DATE DATE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ELECTRICITY_METER
(
    ID BIGSERIAL PRIMARY KEY,
    METER_READING INTEGER NOT NULL,
    DATE DATE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS WATER_HEATING_METER
(
    ID BIGSERIAL PRIMARY KEY,
    METER_READING DECIMAL(5, 3) NOT NULL,
    DATE DATE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS BILLS
(
    ID BIGSERIAL PRIMARY KEY,
    TYPE_BILLS TYPE_BILLS,
    STORE_NAME VARCHAR(100),
    SUM DECIMAL(7, 2) NOT NULL,
    DATE DATE,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
    UPDATED_DATE TIMESTAMP NOT NULL DEFAULT now()
);

