CREATE TABLE IF NOT EXISTS INCOME
(
    ID           BIGSERIAL PRIMARY KEY,
    INCOME       NUMERIC(20, 2) NOT NULL,
    DATE         DATE,
    CREATED_DATE TIMESTAMP     NOT NULL DEFAULT now(),
    UPDATED_DATE TIMESTAMP     NOT NULL DEFAULT now()
);