server:
  port: 8095
spring:
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ha
    driver-class-name: org.postgresql.Driver
    username: cwbp
    password: cwbp
  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    schemas: public
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://localhost:5432/ha
    user: cwbp
    password: cwbp
    default-schema: public
  mvc:
    dispatch-options-request: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/realms/ha-realm/protocol/openid-connect/certs

client:
    url: http://localhost:4200

